default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres123
  pool: 5

development:
  <<: *default
  database: video-app_development


test:
  <<: *default
  database: video-app_test